version: '3.8'

networks:
  traefik-public:
    external: true
  default:

services:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    networks:
      - default
    ports:
      - '389:1389'
      - '636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME?not set admin username}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD?not set admin password}
#      - LDAP_USERS=${LDAP_USERS}
#      - LDAP_PASSWORDS=${LDAP_PASSWORDS}
      - LDAP_ROOT=${LDAP_ROOT}
#      - LDAP_ENABLE_TLS=yes
#      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/openldap.crt
#      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/openldap.key
#      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/openldapCA.crt
    volumes:
      - 'openldap_data:/bitnami/openldap'
    deploy:
      placement:
        constraints:
          - node.labels.service-ldap==true
  openldap-admin:
    image: osixia/phpldapadmin:0.9.0
    networks:
      - traefik-public
      - default
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS="openldap"
      - PHPLDAPADMIN_HTTPS=false
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.docker.network=traefik-public
        # standalone host
        - traefik.http.routers.openldap-https.rule=Host(`openldap-admin.${TRAEFIK_DOMAIN?Variable not set}`)
        - traefik.http.routers.openldap-https.entrypoints=https
        - traefik.http.routers.openldap-https.tls=true
        - traefik.http.routers.openldap-https.service=openldap
        - traefik.http.services.openldap.loadbalancer.server.port=80
        - traefik.http.services.openldap.loadbalancer.server.scheme=http
        - traefik.http.services.openldap.loadbalancer.passhostheader=true

volumes:
  openldap_data:
    driver: local